[features]
seeds = false
[programs.localnet]
turnstile = "4zhxHRB9y1yD7XVP7QCBWYACzqNdi1BVy3S7fZfARFUm"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/Users/tibor/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
